spring.application.name=catlog-services
server.port=8081
server.shutdown=graceful
management.endpoints.web.exposure.include=*
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management.info.git.mode=full